services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
      # Voice chat port
      - "24454:24454/udp"
    environment:
      EULA: true
      VERSION: 1.21.1
      TYPE: NEOFORGE
      JVM_OPTS: "-javaagent:unsup-1.1.4.jar -XX:+UseZGC -XX:+ZGenerational"
      MEMORY: 12G
      SNOOPER_ENABLED: false
      ENABLE_COMMAND_BLOCK: true
      ALLOW_FLIGHT: true
      SPAWN_PROTECTION: 0
      MOTD: "0 Days since last crash"
      SEED: 69
      DIFFICULTY: hard
      OPS: |
        AshAxolotl
    volumes:
      # Use managed volume by default, but can change to a relative path like
      # ./data:/data
      # to use a host directory
      - ./data:/data