name = "WowJongensKijkHetIsEenModpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d07078167d136f3546264338f7f2117080226e48556a4f6cda095b372385c9e8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
unsup = "1.1.4"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
