name = "WowJongensKijkHetIsEenModpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd368c1709c798e85b6d3c0890ca9883c04890ab3b918bfe814524179f7674be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
unsup = "1.1.4"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
no-internal-hashes = false
