name = "WowJongensKijkHetIsEenModpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7280d9fafb61dbfb126bf0f91b0b0de839bae140e609b09aed61c7a1f7eec69a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
unsup = "1.1.4"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
