name = "WowJongensKijkHetIsEenModpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180b35f51785589c9d84003b29ec15ee85843f7df85cb389211f0098e6133813"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
unsup = "1.1.4"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
no-internal-hashes = false
