name = "WowJongensKijkHetIsEenModpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af4adb7668f04b3ee72c732a5a752220c99ebb9c554f1b04ae5b9c7acc4f9c41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
unsup = "1.1.4"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
